### ISSUE TITLE
Please provide a license for this project

### ISSUE THREAD

**Issue by CaveSven** [UCL-CREST/Siamese#17]
Hi and thank you for making your code available on GitHub. I am currently working on launching an open source project for code clone search and would like to expand on your work. However, I am not able to do so unless you would be willing to add a license statement. 

Thanks, also for the great review of the state-of-the-art in [Code Similarity and Clone Search in Large-Scale Source Code Data](https://cragkhit.github.io/publications/chaiyong_thesis.pdf), from which I learned a lot.

**Comment by cragkhit** [comment]
Hi @CaveSven. I'm glad to hear that you would like to continue working on Siamese. I've now added the GPL license. If you have any problems/questions, please let me know.

Also, thanks for the reading my thesis :)

**Comment by CaveSven** [comment]
I appreciate it, thanks!

**Comment by CaveSven** [comment]
Hi @cragkhit,
would it also be possible to provide this with an Apache 2.0 license?

**Comment by cragkhit** [comment]
@CaveSven I've now added Apache 2.0 license to the project.

**Comment by CaveSven** [comment]
This is great :+1:
