### ISSUE TITLE
About Recall Experiment

### ISSUE THREAD

**Issue by coderZMR** [UCL-CREST/Siamese#24]
Hi, my friend. We've been studying your Siamese tool recently. In the Recall experiment, we saw your test reports on BigCloneBench, and we found that you found 5,2027,201 clones(min lines 6, min tokens 50). But if use the 14780 methods in references/bcb_chosen_clones as queries and search on the ijadataset/bcb_reduced, there are only 13,302,000 clone pairs(query/answer combination, 900 answers per query) at most. I don't know what the problem is. Can you help me?

**Comment by cragkhit** [comment]
Hi @coderZMR. I've used the full BigCloneBench dataset for the experiment. If you use the reduced version, the number of files will be much smaller and that would explain why the number of clones are also fewer. 

Can you let me know specifically which part of the paper that you're referring to?

**Comment by coderZMR** [comment]
Thanks for the reply. The question referred to in the "6.2.2 BigCloneBench" section of the paper, where it was stated that you used 14,780 methods as queries and took the first 900 results from each query to form a clone pair. Did you do this on the full BigCloneBench?

**Comment by cragkhit** [comment]
@coderZMR Yes I used the full BigCloneBench for the experiment in Siamese paper. Can you please tell me more where did you get the number 5,2027,201 from?

**Comment by coderZMR** [comment]
Thanks for the reply. In the file "siamese_eval_2018-08-18_6lines.txt" in the directory "Siamese/results/results_for_rq2/recall", the value "#Clones" under the information "Tool" in this file is 52027201.

**Comment by cragkhit** [comment]
@coderZMR Hi. Thanks for the explanation. The no. of clone pairs from Siamese is 14,780 * 900 = 13,302,000 as you mentioned. I've double checked the clone pair file that I created from the Siamese result and gave to BigCloneEval for recall evaluation. It contains 13,302,000 pairs.

The part below in the file `https://github.com/UCL-CREST/Siamese/blob/master/results/results_for_rq2/recall/siamese_eval_2018-08-18_10Lines.txt`, which contains the number 52027201, is generated by BigCloneEval. Thus, I'm not sure that this number means as well. 

```
-- Tool --
       Tool: 1 - Siamese
Description: Siamese clone search
    #Clones: 52027201
```

**Comment by coderZMR** [comment]
Hi. I want to run Siamese again on BigCloneBench, which includes two stages: indexing and search for testing recall. I want to ask whether the code warehouse currently contains code for testing recall? And what are the parameter values that need to be set in these two parts? I see that the current warehouse contains the "configs" package. I currently use "config_bcb_index.properties" for indexing and "config_bcb_search.properties" for searching. Is this correct?

**Comment by cragkhit** [comment]
Hi @coderZMR. Yes I think the two configurations are correct. I evaluated the recall using BigCloneEval https://github.com/jeffsvajlenko/BigCloneEval.
