### ISSUE TITLE
Error with Java 10.0.2

### ISSUE THREAD

**Issue by gapgag55** [UCL-CREST/Siamese#7]
I got Elasticsearch error while following the README.md with command 
`sudo apt-get install default-jdk`

The latest version of JDK is 10.0.2 is not complatible with Elasticsearch as the error below

```
./elasticsearch-2.2.0/bin/elasticsearch
Unrecognized VM option 'UseParNewGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
I solved the problem by installing JDK 8 and changed the JAVA_HOME environment

`sudo apt-get install openjdk-8-jdk`

In addition, I also got the error 
`Exception in thread "main" java.lang.RuntimeException: don't run elasticsearch as root.`

I solved with command
`./elasticsearch-2.2.0/bin/elasticsearch -Des.insecure.allow.root=true`

OS: MacOS
Platform: Docker
Image: Ubuntu

**Comment by cragkhit** [comment]
Thanks for reporting this!
